global:
  checkNewVersion: true

api:
  dashboard: true

accesslog: {}

log:
  level: "INFO"

entryPoints:
  http:
    address: :80

  https:
    address: :443

providers:
  file:
    filename: /etc/traefik/traefik-file.yml

  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true